### ISSUE TITLE
fix.New() / Init() shouldn't accept 0 as denominator

### ISSUE THREAD

**Issue by ainvaltin** [fncodr/godbase#3]
fix.New() / Init() probably shouldn't accept 0 as denominator, ie

    f := fix.New(425, 0)
    fmt.Println(f.String())

will result in "panic: runtime error: integer divide by zero" when converting to string (but should fail when constructing new value?)

**Comment by fncodr** [comment]
Agree, added a precond check to fix.Init here: b4fd6de.
Thanks
